[theme]
theme = "dracula"
[icons]
icons = "awesome6"

[[block]]
block = "net"
format = "$icon $device $ssid $signal_strength $ip "
format_alt = "$icon $device $ssid $signal_strength $ipv6 "
interval = 20

[[block]]
block = "memory"
format = "$icon$mem_used/$mem_avail($mem_used_percents) "
format_alt = "$icon_swap$swap_used/$swap_total($swap_used_percents) "
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 5
format = "$icon$utilization $frequency "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = "$icon $available free"
format_alt = "$icon $used used"
alert_unit = "GB"
alert = 50
warning = 40
interval = 60

[[block]]
block = "xrandr"

[[block]]
block = "custom"
cycle = [ 
'echo India $(date +"%a %d %B %l:%M %p")', 
'echo Germany $(TZ=Europe/Berlin date +"%a %d %B %l:%M %p")',
'echo New York $(TZ=America/New_York date +"%a %d %B %l:%M %p")'
]
interval = 10
[[block.click]]
button = "left"
cmd = "<command>"

[[block]]
block = "battery"
format = "$icon $percentage {$time |} {$power |}"
missing_format = ""
interval = 5
driver = "upower"
#hide_missing = true


[[block]]
block = "menu"
text = "\uf011"
[[block.items]]
display = " -&gt;   Sleep   &lt;-"
cmd = "systemctl suspend"
[[block.items]]
display = " -&gt; Power Off &lt;-"
cmd = "poweroff"
confirm_msg = "Are you sure you want to power off?"
[[block.items]]
display = " -&gt;  Reboot   &lt;-"
cmd = "reboot"
confirm_msg = "Are you sure you want to reboot?"


